### ISSUE TITLE
FlashPatch.exe???

### ISSUE THREAD

**Issue by vern4760** [darktohka/FlashPatch#1]
I downloaded and extracted the .zip file.  Unable to find FlashPatch.exe

**Comment by darktohka** [comment]
Hi there @vern4760!

Re-download the .zip file. The FlashPatch.exe is in the archive:

**Comment by vern4760** [comment]
I tried again.  No file named "FlashPatch.exe" is located in "FlashPatch-master.zip" or any of its subfolders.  There is "FlashPatch.sln" and "FlashPatch.csproj".  I can't find any ".exe" files anywhere.  [It isn't listed in the directories shown on this site either.]

**Comment by krum110487** [comment]
You are downloading the code, not the executable.
https://github.com/darktohka/FlashPatch/releases/tag/v1.3 get the ".zip"

here is a direct link as of today:
https://github.com/darktohka/FlashPatch/releases/download/v1.3/FlashPatch.zip

**Comment by vern4760** [comment]
Someone else sent me the right link too.  

Used the patch.  The screen saver works now.
Thanks.
