### ISSUE TITLE
Flash Patch says it worked, but is not working on Chrome or Edge.

### ISSUE THREAD

**Issue by Hypno7767** [darktohka/FlashPatch#11]
After closing all my browser tabs and patching with FlashPatch, no difference is made, and Flash Player does not work. On chrome, the feature seems to be completely removed and does not appear no matter what I do, however with Edge, when I press allow once and it reloads, Flash Player does not load and the place where flash should be is blank.

**Comment by Hypno7767** [comment]
![image](https://user-images.githubusercontent.com/33670815/112412070-4b68cb80-8cf4-11eb-8cc3-d332fd5b3604.png)
This is an image of what FlashPatch says it patched. Internet Explorer does not work with Flash Player still.

**Comment by Hypno7767** [comment]
Installing Firefox and restoring and repatching again does not enable it for Firefox.

**Comment by Hypno7767** [comment]
Installing flash player via an installer, restoring and repatching will cause this
![image](https://user-images.githubusercontent.com/33670815/112413786-2a55aa00-8cf7-11eb-993b-13f0e60c985c.png)
however, only Internet Explorer can be used and Firefox will pretend as if the flash content does not exist

**Comment by Hypno7767** [comment]
Personally I think It's quite odd how it successfully patched the plugin, however Firefox ignores this and does not display any evidence of the flash content existing. This could possibly be an issue of Firefox not being previously installed, and therefore not having flash built into it from the start. I don't really know what I could do to fix it though.

**Comment by darktohka** [comment]
Please let me know what version of Firefox you're using.

Firefox 85 completely removed support for Flash. To keep using Flash, you must install [Firefox ESR](https://www.mozilla.org/en-US/firefox/enterprise) (recommended, will support Flash until [2021-10-05](https://wiki.mozilla.org/Release_Management/Calendar)) or an older version of Firefox (not recommended). Alternatively, use a Firefox fork like [Basilisk Browser](https://www.basilisk-browser.org) to keep using Flash.

As for the Internet Explorer issue, please send me a screenshot of the contents of these folder:

`C:\Windows\SysWOW64\Macromed\Flash`
`C:\Windows\System32\Macromed\Flash`

**Comment by Hypno7767** [comment]
Internet Explorer works perfectly fine. I am sorry for not clarifying that. I will most likely install Basilisk as it seems like a permanent solution to playing flash games on browser again. Thank you so much for your support. I can finally get back to playing all my favorite games again.

**Comment by darktohka** [comment]
Similarly, Chrome has also removed support for Flash. But I'm working on an experimental solution for running Flash on recent Chrome versions. I'll keep you updated, but don't get your hopes up.
