### ISSUE TITLE
Strange window behavior inside flash frame 

### ISSUE THREAD

**Issue by Sadi58** [darktohka/FlashPatch#14]
Thanks to this patched flash player plugin, I can access archives of a daily newspaper using Waterfox plus "libflashplayer.so" in "flash_player_patched_npapi_linux.x86_64.tar.gz".
However, a strange window behavior (a black area covering the lower half of the viewing pane) reduces the viewing height badly and also prevents viewing of a good top part, as seen in the left screenshot below.
The same image can be seen properly in Puffin mobile web browser featuring builtin flash plugin as seen in the right.
![waterfox-puffin](https://user-images.githubusercontent.com/6375934/117452711-c3115380-af4c-11eb-9dff-0bd567af6706.jpg)

**Comment by darktohka** [comment]
Hey, can you send links to the SWFs for testing?

**Comment by darktohka** [comment]
Hey! Thanks for providing these login credentials.

Unfortunately I can't reproduce the issue. I've tried the following configurations:
- Waterfox on Manjaro Linux (KDE)
- Basilisk Browser on Manjaro Linux (KDE)
- Basilisk Browser on Windows 10
- Waterfox on Windows 10

They all render correctly:
![image](https://user-images.githubusercontent.com/16326697/120048538-0e84c200-c020-11eb-8ee8-25c994c238f7.png)

I'm not sure if this is a bug we can fix in the first place, it'd have to be something Adobe would fix.

What display manager / window system are you using? What distro with which desktop environment? Might be a bug with the desktop environment.

**Comment by Sadi58** [comment]
Sorry, I forgot to provide some system information as well.
I'm using Waterfox G3.2.1 (64-bit) based on Gecko 78.10.0, KDE neon 5.21.5 with X11 display manager.
I have the same problem in a Live Session of KDE neon.
So it's probably because of a stupid mistake I'm making in installing Waterfox and Flash plugin.
These are the steps I've followed:
1. Install browser plugin package with the command `sudo apt install browser-plugin-freshplayer-pepperflash` (actually I get the same results with or without this - probably it's for Chromium-based browsers only).
2. Download https://github.com/darktohka/clean-flash-builds/releases/download/v1.7/flash_player_patched_npapi_linux.x86_64.tar.gz
3. Copy `libflashplayer.so` to `/usr/lib/mozilla/plugins/` (installing the standalone flash player also makes no difference as I remember)
4. Download https://cdn.waterfox.net/releases/linux64/installer/waterfox-G3.2.1.en-US.linux-x86_64.tar.bz2
5. Extract contents to `/opt`
6. Start `/opt/waterfox/waterfox`
I also installed Manajaro KDE on another laptop, but I couldn't even get the plugin showing up following the steps above (unfortunately I couldn't get anywhere after enabling AUR and successfully refreshing community.db and community.files). It seems Arch Linux is still too complicated for me although I regard myself a bit above average level Linux users. ;-)
I understand if you don't consider this an issue to be attended by you...

**Comment by darktohka** [comment]
Hey there!

I downloaded KDE neon 5.21.5 and installed it on my machine (using your steps 2 to 6). Only difference is that I chowned the /opt/waterfox folder to my user before running it.

Unfortunately, I do not see the strange black area that you do.

Might this be a video driver issue?

**Comment by Sadi58** [comment]
I also performed two tests on another laptop with hybrid Intel/AMD graphics card with KDE neon Live Session.
I was hopeful with the command `env DRI_PRIME=1 "/home/neon/.local/opt/waterfox/waterfox"` but it was the same again.
The plugin actually works except this particular frame/panel configuration.
I think I'll just give up on this dumb old archive. ;-)
Thanks for your efforts!

**Comment by n0samu** [comment]
This looks very much like a display scaling issue to me. If you have display scaling enabled in KDE Neon's settings, you could try turning it off, if this is still an issue.

**Comment by Sadi58** [comment]
@n0samu Thanks, but no, I haven't touched display scaling, and this happens to me when testing with KDE neon live session with all default settings.
After @darktohka reported that this problem couldn't be reproduced on a fresh install of KDE neon a year ago, it seems this is a weird problem related my particular hardware/software configuration, so I should better close it.
