### ISSUE TITLE
Support for the latest Flash Player version 34.0.0.184

### ISSUE THREAD

**Issue by ShokaKurumi** [darktohka/FlashPatch#16]
It seems that FlashPatch can't recognize the latest Flash Player, version 34.0.0.184.

**Comment by darktohka** [comment]
Thanks for letting me know about the new version. I'll be working on patches for 34.0.0.184 throughout today.

**Comment by jasonliul** [comment]
Anything wrong with 34.0.0.184? seems patch has been delayed a few days.

**Comment by darktohka** [comment]
@jasonliul Just a fair amount of binaries to patch (right now, 20 binaries per release including each Release variant, Debug variants, OS-specific variants and standalone players). Patches are now released for 34.0.0.184 and clean builds and CleanFlash installer are on the way as well.

**Comment by jasonliul** [comment]
Thanks buddy, we enjoy yr excellent job.
