### ISSUE TITLE
New version 34.0.0.184

### ISSUE THREAD

**Issue by jasonliul** [darktohka/FlashPatch#19]
Offline installler
https://www.upload.ee/files/13384007/AdobeFlashPlayer_34.0.0.184.7z.html

No need to rush, i don't mean it. :)

**Comment by darktohka** [comment]
Thank you for the heads-up! However, the new version is 34.0.0.192, not 34.0.0.184.

I've already begun working on this version an hour ago.

**Comment by darktohka** [comment]
New version 34.0.0.192 has been released:
https://github.com/darktohka/FlashPatch/releases/tag/v1.11
https://github.com/darktohka/clean-flash-builds/releases/tag/v1.15
https://github.com/CleanFlash/installer/releases/tag/v1.5

**Comment by jasonliul** [comment]
Bravo!
