### ISSUE TITLE
flashpatch wont detect my chrome

### ISSUE THREAD

**Issue by BubblyPopper** [darktohka/FlashPatch#2]
i have 64 bit chrome and the latest flash (integrated) but flashpatch only patches the activex part of flash (ie)
how do i fix this?

**Comment by darktohka** [comment]
If FlashPatch does not find your version of the Chrome Flash Player plugin, then try finding libpepflashplayer.dll (or pepflashplayer.dll) manually. You can use a program such as [Search Everything](https://www.voidtools.com/downloads) to accomplish this.

Once found, please let me know where your Flash Player installation was. Adjustments will be made afterwards. (full path, including filename, please)

When you've found pepflashplayer, you can use the "Patch File..." feature to browse for the file and patch it manually. Make sure your browser is not open at this point.

Please also let me know what kind of browser you are using!

Thank you.

**Comment by q00u** [comment]
If your Chrome version is higher than 87, I think it doesn't have flash at all anymore.

**Comment by darktohka** [comment]
Any update on this issue?

**Comment by Username8451** [comment]
I tried patching the file manually like you said, but it didn't work for me. It says that the binaries have not been patched, as compatible patches don't exist.

**Comment by darktohka** [comment]
@Username8451 Can you upload the file? https://gofile.io/

**Comment by Username8451** [comment]
@darktohka https://gofile.io/d/QkWk9R < here you go

**Comment by darktohka** [comment]
@Username8451 Seems like a non-issue.

![image](https://user-images.githubusercontent.com/16326697/107623472-0b78e800-6c62-11eb-884f-006b443140e9.png)

Using the latest version of FlashPatch, this binary can be patched using the generic patch.

However, it would be smarter to update to the LATEST version of Flash, because 32.0.0.453 is not the latest version. 32.0.0.465 is, and is officially supported by FlashPatch:

https://web.archive.org/web/20201220001753/http://fpdownload.adobe.com/get/flashplayer/pdc/32.0.0.465/install_flash_player.exe

**Comment by Username8451** [comment]
I got Flash 32.0.0.465, as well as FlashPatch 1.4, but it still doesn't fix Chrome.

**Comment by desbest** [comment]
As seen in the image above, the Pepper/PPAPI flash plugin was successfully patched, so Flashpatch works.

Chrome versions 45 and above have removed NPAPI support which is what's used to run web browser plugins (eg. Flash, Shockwave, Unity, Acrobat, Google Earth, Silverlight, Java. Facebook Video, etc)
Chrome made an exception for flash in the past, but that ended at Chrome version 87 and above.

So you will have to use a different web browser. I recommend you install [Basilisk](http://basilisk-browser.org) as that supports NPAPI plugins.

**Comment by Username8451** [comment]
For me, I just installed NPAPI Flash 32.0.0.371 and Pale Moon.
