### ISSUE TITLE
Support on "maybe" November release of Flash Player

### ISSUE THREAD

**Issue by AsakaAkemi** [darktohka/FlashPatch#22]
Here's the "maybe" November release of Flash Player, version 34.0.0.201, issued by Adobe on Oct 22, 2021.
[Click here to download this release.](https://shiedf-my.sharepoint.com/:u:/g/personal/9722_office563_club/EVGRyBroS_dPjk1KdugBpOMBQG3we7h-JaYUDjDSSixRVw?e=YcOpzg)
But this release is not supported by FlashPatch yet.

**Comment by darktohka** [comment]
Hello! Where did you download this release from?

**Comment by darktohka** [comment]
For FlashPatch to be able to support this version, we'll need to have the debug installers/binaries, as well as the standalone Flash Player (release+debug).

**Comment by AsakaAkemi** [comment]
[Here's the Debug version of this new release.](https://shiedf-my.sharepoint.com/:u:/g/personal/9722_office563_club/ESCUHh6Y0CxCvk8VJK1N0usBXqY8sdDS2e1xKf4_Fab02A?e=uiiTwd)
But there's no standalone Flash Player available yet.

**Comment by darktohka** [comment]
Thank you for the help!

https://github.com/darktohka/FlashPatch/releases/tag/v1.12 is out. You should be able to use this version to patch your files.

**Comment by AsakaAkemi** [comment]
34.0.0.201 is now available to the public.

**Comment by AsakaAkemi** [comment]
macOS version and Windows standalone version (release+debug) are available now.

**Comment by darktohka** [comment]
Thanks, added support for these as well.

**Comment by tomay3000** [comment]
Thank you very much.
