### ISSUE TITLE
Support on planned December release of Flash Player

### ISSUE THREAD

**Issue by AsakaAkemi** [darktohka/FlashPatch#23]
Here's the planned December release of Flash Player, version 34.0.0.209, issued by Adobe on November 25, 2021.

[Download Link](https://shiedf-my.sharepoint.com/:u:/g/personal/9722_office563_club/EWrkkZ5kBdRDlgAVxU-qtgYBE8Azku0C-lIqavRO94ZGqw?e=gb9jb9)

Available Version:
Windows Active X + PPAPI + NPAPI (Release & Debug)

Other version will be available on December 14, 2021. (Planned time).

FlashPatch has not support this version yet.

**Comment by darktohka** [comment]
Thank you!

Both FlashPatch and clean-flash-builds has been updated for revision 209.

**Comment by AsakaAkemi** [comment]
A new version of Flash Player December release is available. (Version 34.0.0.211, issued by Adobe on December 6, 2021)

Available Version:
Windows Active X + PPAPI + NPAPI (Release & Debug)

[Download Link](https://shiedf-my.sharepoint.com/:u:/g/personal/9722_office563_club/EcObX56TY4FDtT8UuVlPdacBLX-fRQsirR6xRtQ6yklahQ?e=QGQYJd)
