### ISSUE TITLE
Support on Flash Player version 34.0.0.211

### ISSUE THREAD

**Issue by AsakaAkemi** [darktohka/FlashPatch#24]
Flash Player December release is now public available. (Version 34.0.0.211, issued by Adobe on December 6, 2021)

FlashPatch has not support this version yet.

**Comment by jasonliul** [comment]
Official installer 34.0.0.211
https://www.flash.cn/flashplayer/3400211/install_flash_player_ax_cn.exe
https://www.flash.cn/flashplayer/3400211/install_flash_player_cn.exe
https://www.flash.cn/flashplayer/3400211/install_flash_player_ppapi_cn.exe

**Comment by darktohka** [comment]
Thank you. The latest version should support 34.0.0.211 now.

**Comment by Vangelis66** [comment]
@darktohka wrote: 

> The latest version **should support 34.0.0.211** now.

Hi :smile: ; many thanks for this tool; however...
1. I downloaded the official Chinese NPAPI setup from 
`https://www.flash.cn/flashplayer/3400211/install_flash_player_cn.exe`
2. I extracted it to disk with "[Adobe Flash Player Installer unpacker](https://github.com/darktohka/FlashPatch/files/7731007/AFPIunpack.zip)" (other tools may be available)
VirusTotal link:
`https://www.virustotal.com/gui/file/8b683921377731905a81751765169718f06212eb7e1cb40d0b66c6baa3a5b60c` => detection rate **1/66** (a false positive! :wink:)
3. I isolated original DLL file **NPSWF32_34_0_0_211.dll** (32-bit), here's the (unaltered) file sig: 

![unpatched](https://user-images.githubusercontent.com/9669492/146464608-74cf5f20-b415-4dbc-a14b-3244264d5440.jpg)

4. I then launched latest **FlashPatch.exe** (v1.14) and wanted to use the `Patch File...` feature!
5. When I selected (file picker windows popup) the aforementioned **unpatched** DLL, I got the message below: 

![FP-NW](https://user-images.githubusercontent.com/9669492/146464978-fe907fe7-d9e3-4830-aa93-752a99576d1c.jpg)

... and when I exited FP, indeed **the DLL was left untouched**, i.e. **unpatched**, with an intact file sig...

The test was carried out on two different systems, a) Windows Vista SP2 x86, with .NET FW 4.6.2 b) Windows 7 SP1 x64, with  .NET FW 4.6.1; AIUI, .NET FW **4.5** is the minimum version required; can you advise why I failed to patch the DLL myself? 
FWIW, the already patched DLLs offered [here](https://github.com/darktohka/clean-flash-builds/releases/tag/v1.20) work as they should, on both systems! :+1: 

Any further insight will be appreciated :smile: 
Many thanks, festive wishes, keep safe from "omicron"!

**Comment by darktohka** [comment]
@Vangelis66 This bug should be fixed in the latest version, please test and let me know. :)

**Comment by Vangelis66** [comment]
> This bug should be fixed in the latest version, please test and let me know.

Thanks for your reply, unfortunately nothing changed with the advent of `FlashPatch-v1.15.exe` 😭 

I'm attaching below the original, un-patched, x86 NPAPI dll of **34_0_0_211**: 

[NPSWF32_34_0_0_211.zip](https://github.com/darktohka/FlashPatch/files/8219053/NPSWF32_34_0_0_211.zip) (zipped)

OS: Windows Vista SP2 **32-bit**, fully patched + select WS2008SP2 updates
.NET Framework: **4.6.1** (32-bit) with MS patches installed manually

`FlashPatch_v1.5.exe` launches fine here: 

![t1](https://user-images.githubusercontent.com/9669492/157561693-3d8f526f-602c-44b4-9510-f58e88e5c99e.jpg)

I select the DLL to be patched (identical to the DLL attached above), but as soon as I click `Open`, FP informs me that: 

![t2](https://user-images.githubusercontent.com/9669492/157561916-7d2b3e56-9fb5-4f24-90e8-451d3ccdd2a7.JPG)

... and the DLL is left untouched... 😞 

If it isn't clear already, I want to patch Chinese Flash (32.0.0.211 here) **without having to first install it in my system** (but via first extracting NPAPI+PPAPI dlls out of their respective installers...).

Any insight is welcome 😄

**Comment by darktohka** [comment]
Thank you for your patience @Vangelis66.

Unfortunately the previous patch I made to fix your issue was an incomplete one.

The following release v1.15.1 should resolve your issue: https://github.com/darktohka/FlashPatch/releases/tag/v1.15.1

By the way, if you want to install Flash to your system, try using Clean Flash Installer, it is the most convenient option: https://gitlab.com/cleanflash/installer/-/releases

**Comment by Vangelis66** [comment]
> The following release v**1.15.1** should resolve your issue: 

At long last: 

![FP](https://user-images.githubusercontent.com/9669492/158082834-2fa248ca-d562-4bca-b1ca-031e780b6b05.JPG)

:+1: :tada: :rocket: 

> if you want to install Flash to your system, 
> try using **Clean Flash Installer**, it is the most convenient option: 

Thanks :smiley_cat: , but I'm already aware of it :wink: , as well as of [Clean Flash Player](https://github.com/darktohka/clean-flash-builds) builds :+1:  ... 
In fact, I'm using the **latter** as it is, for "**portable**" Flash installations (portable **Serpent 52**/**360E**Ev11-12-13 installations) ...  

What I was, in fact, trying to do, but hampered by the reported bug :angry: , was to verify/replicate the functionality of **FlashPatch** _myself_, having already access to the **original Chinese** (unpatched) setup, but without wanting to first install it systemwide... I hope it's now clear! 
Thanks for fixing this, please do continue this nice project!

Kindest regards :smile:
