### ISSUE TITLE
Windows 11 Arm

### ISSUE THREAD

**Issue by cadedoescode** [darktohka/FlashPatch#26]
I'm trying to run a game that uses clean flash on windows 11 arm. It is not working.

The game works perfectly on (x86) windows 10, windows 7, etc.

Is it simply incompatible or is windows blocking the flash player etc. Thanks for the help.

**Comment by darktohka** [comment]
Internet Explorer was removed from Windows 11. Most likely your game is trying to use the IE engine to run Flash.

To fix this issue you must copy the respective `ieframe.dll` files from a Windows 10 installation into `C:\Windows\System32` and `C:\Windows\SysWOW64`.

**Comment by darktohka** [comment]
Can you tell us what program you are trying to run?

**Comment by cadedoescode** [comment]
I got it to work. I just had it in the wrong folder in my windows 11 vm. Sorry for the confusion, issue withdrawn.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
