### ISSUE TITLE
Linux Flash Projector

### ISSUE THREAD

**Issue by moriel5** [darktohka/FlashPatch#27]
This isn't really something critical, since the Flash Projector can easily be used in a locked down environment, however I have noticed that only Windows releases include it.

Are there any Linux (and MacOS) 34.x versions of the Flash Projector?

**Comment by AsakaAkemi** [comment]
No. Adobe only released Windows version of Flash 34 Projector.

**Comment by moriel5** [comment]
Thanks, that certainly makes sense (and is unfortunate, but not really necessary).

I guess I can close this now.
