### ISSUE TITLE
Support for Adobe Flash Player version 34.0.0.231

### ISSUE THREAD

**Issue by AsakaAkemi** [darktohka/FlashPatch#28]
Here's the March 2022 Release of Adobe Flash Player, version 34.0.0.231.
[Download Here](https://shiedf-my.sharepoint.com/:u:/g/personal/9722_office563_club/ERn8B6rSr0VNjH7VHBytfQcBnUAgzJL1K0oLzrHJIXqEWA?e=i63lQq)

Available version:
Windows Active X + PPAPI + NPAPI (Release + Debug)
Other version will be available on March 8, 2022 (China Standard Time).

Please add support for this release.

**Comment by darktohka** [comment]
Thank you, working on it.

**Comment by darktohka** [comment]
Thank you for being patient! FlashPatch v1.15 has been released with 34.0.0.231 support:  https://github.com/darktohka/FlashPatch/releases/tag/v1.15

Clean Flash builds are available at: https://github.com/darktohka/clean-flash-builds/releases/tag/v1.22

Clean Flash Installer is available at: https://gitlab.com/cleanflash/installer/-/releases/34.0.0.231

**Comment by AsakaAkemi** [comment]
34.0.0.231 is now publicly available.
Windows Projector:
https://www.flash.cn/cdm/latest/flashplayer_sa.exe
https://www.flash.cn/cdm/latest/flashplayer_sa_debug.exe
macOS Release (PPAPI+NPAPI)
https://www.flash.cn/flashplayer/latest/install_flash_player_osx_ppapi.dmg
https://www.flash.cn/flashplayer/latest/install_flash_player_osx.dmg

**Comment by darktohka** [comment]
Thank you! Working on it, will let you know when it's ready.

**Comment by darktohka** [comment]
The new version of FlashPatch is available at:
https://github.com/darktohka/FlashPatch/releases/tag/v1.15.1

Windows builds are available at:
https://github.com/darktohka/clean-flash-builds/releases/tag/v1.22

Mac builds are available at:
https://github.com/darktohka/clean-flash-builds/releases/tag/v1.23

Clean Flash Installer has been updated at:
https://gitlab.com/cleanflash/installer/-/releases/34.0.0.231

**Comment by AsakaAkemi** [comment]
Thank you!
