### ISSUE TITLE
Support on Flash Player Version 34.0.0.242

### ISSUE THREAD

**Issue by ayakamiho** [darktohka/FlashPatch#29]
Here's the latest Flash Player release, version 34.0.0.242, which is planned to be released on May 2022.
[Download Here.](https://shiedf-my.sharepoint.com/:u:/g/personal/9722_office563_club/EferIqIOBJtPpriE4bVAlrkBHY-Zjv85IHO9nd9UyqM7Jg?e=sN72PO)
Please add support for this release. Thank you!

**Comment by darktohka** [comment]
Thank you for being patient

FlashPatch v1.16 has been released with 34.0.0.242 support: https://github.com/darktohka/FlashPatch/releases/tag/v1.16

Clean Flash builds are available at: https://github.com/darktohka/clean-flash-builds/releases/tag/v1.24

Clean Flash Installer is available at: https://gitlab.com/cleanflash/installer/-/releases/34.0.0.242
