### ISSUE TITLE
Firefox is "fighting back"

### ISSUE THREAD

**Issue by vern4760** [darktohka/FlashPatch#3]
FlashPatch got my screen saver working and it worked with Firefox for a while, but now Flash games are blocked on Firefox again.  Firefox might have taken additional measures.  [The FlashPatch installation program confirmed that it is patched into Firefox, so there must be something new that keeps it from working.]

**Comment by jools5000** [comment]
Firefox 85+ no longer supports any plugins (including Flash).  All mainstream browsers are removing support for plugins, since Flash was the last plugin allowed there is no need to keep the code.  Firefox ESR should still support Flash until later this year.

**Comment by darktohka** [comment]
This is not something that we can fix. Firefox 85, released on January 26, 2021, completely removes Flash support. To keep using Flash on Firefox, either download [Firefox ESR](https://www.mozilla.org/en-US/firefox/enterprise), which will support Flash until 2021-10-05 (according to the [Release Calendar](https://wiki.mozilla.org/Release_Management/Calendar)) or migrate to [Basilisk Browser](https://www.basilisk-browser.org), which will support NPAPI plugins, including Flash indefinitely. [Basilisk Browser](https://www.basilisk-browser.org) is built upon a newer Firefox base by the Pale Moon team.
