### ISSUE TITLE
Is there a newer version of Adobe Flash Player v34.0.0.192 with original installer?

### ISSUE THREAD

**Issue by RemixPL1994** [darktohka/FlashPatch#35]
Hello @darktohka is there a newer version of Adobe Flash Player v34.0.0.192 with original installer?

I currently have Adobe Flash Player v34.0.0.192 on my disk in three separate versions for Firefox l NPAPI and Opera, Chrome l PPAPI and Internet Explorer l ActiveX.

![obraz](https://user-images.githubusercontent.com/52541621/183740646-be01a203-c98c-46e5-aba0-7ce455b34d23.png)

Am I able to get a newer installer than the one I currently have so that I can continue to install it independently in three separate versions as the original installer?

By original installer I mean this look:

![obraz](https://user-images.githubusercontent.com/52541621/183740936-087d90e7-50ae-4c13-9b86-1b0c5eedff40.png)

![obraz](https://user-images.githubusercontent.com/52541621/183741269-f9d26e23-f121-4315-9ac8-c39dc3751364.png)

I would like something like this for the latest flash version that exists but I'm not interested in AiO, repack etc.

Can you tell me something about it?

Maybe on e-mail or Discord if it's not a topic for public conversations?

Regards.

**Comment by MikiHikaru** [comment]
Here's the latest installer of Adobe Flash Player, version 34.0.0.267.
ActiveX: https://www.flash.cn/flashplayer/3400267/install_flash_player_ax_cn.exe
NPAPI: https://www.flash.cn/flashplayer/3400267/install_flash_player_cn.exe
PPAPI: https://www.flash.cn/flashplayer/3400267/install_flash_player_ppapi_cn.exe
It is recommend to disconnect internet connection before install.

**Comment by MikiHikaru** [comment]
I think it's a locked version.

**Comment by ShinjoKurumi** [comment]
I think this issue is now solved, and should be closed now.
