### ISSUE TITLE
Support for Flash Player v34.0.0.277

### ISSUE THREAD

**Issue by HanawaMica** [darktohka/FlashPatch#37]
Here's the latest Flash Player release, version 34.0.0.277, which is planned to be released on November 2022.
[Download Here.](https://shiedf-my.sharepoint.com/:u:/g/personal/9722_office563_club/ESDT8VsHHUhLkOnTR0ZLaeYBofewS67wfm57SW3a6Y7hZQ?e=kINVS2)
Please add support for this release. Thank you!

**Comment by darktohka** [comment]
Hey there!

FlashPatch has been updated with support for 34.0.0.277: https://github.com/darktohka/FlashPatch/releases/tag/v1.19

Clean builds are available at: https://github.com/darktohka/clean-flash-builds/releases/tag/v1.30

Clean Flash Installer for this release is available at: https://gitlab.com/cleanflash/installer/-/releases/34.0.0.277 or https://bluepload.unstable.life/cleanflash3400277installer.exe

Have fun!

**Comment by HanawaKurumi** [comment]
Thanks!

**Comment by HanawaMica** [comment]
Windows Standalone Player & macOS version are available on flash.cn now. Please add support for them. Thanks!

**Comment by darktohka** [comment]
Thank you.

FlashPatch is available at: https://github.com/darktohka/FlashPatch/releases/tag/v1.19.1

Clean builds are available at: https://github.com/darktohka/clean-flash-builds/releases/tag/v1.30

Clean Flash Installer is available at: https://gitlab.com/cleanflash/installer/-/releases/34.0.0.277 or https://bluepload.unstable.life/cleanflash3400277installer1.exe

**Comment by HanawaMica** [comment]
Thank you!
