### ISSUE TITLE
Support for some Chinese Flash Player versions

### ISSUE THREAD

**Issue by HiganMica** [darktohka/FlashPatch#38]
Here're some versions of Chinese Flash Player that are not supported by FlashPatch yet. Please add support for them. Thanks!

Version List:
34.0.0.92 (Windows + Linux)
34.0.0.105 (Windows Only)
34.0.0.110 (Windows Only)
34.0.0.282 (Windows Only) (March 2023 New Release)

Unfortunately, standalone players are not available except version 34.0.0.92.

Download link:
https://asakaakemi-my.sharepoint.com/:u:/g/personal/admin_miraclenet_ax_lt/EQ9zXyxaRqBNqH0kiKtCo_kBcpTDY81pS_gfRIM27k4Mag?e=JgSBpa

**Comment by darktohka** [comment]
Thank you! I've added support for 34.0.0.282. Though, I don't see why I'd want to spend time bothering with these old versions. Eventually I want to create an auto-patcher that can patch the binaries without my intervention.
