### ISSUE TITLE
Update to support Flash Player 34.0.0.323

### ISSUE THREAD

**Issue by teknixstuff** [darktohka/FlashPatch#54]
There's a new version of flash player out. Any chance you could update FlashPatch to work with it?

**Comment by teknixstuff** [comment]
[NPSWF64_34_0_0_323.zip](https://github.com/user-attachments/files/18136071/NPSWF64_34_0_0_323.zip)
Here's the 64-bit NPAPI binaries for the new version, if it helps. The NPAPI files are quite hard to download with this version, as Flash Center cannot install them anymore.

**Comment by teknixstuff** [comment]
Oh also, if you have any idea what `FlashUtil64_34_0_0_323_Plugin.dll` and `FlashUtil64_34_0_0_323_Plugin.exe` are for and why they are required for NPAPI flash to run, that would be nice to know. Also might be worth adding them into Clean Flash Player, as currently they are not provided, causing NPAPI flash to not work.

**Comment by jasonliul** [comment]
Official installer 34.0.0.323
https://www.flash.cn/flashplayer/3400323/install_flash_player_ax_cn.exe
https://www.flash.cn/flashplayer/3400323/install_flash_player_cn.exe
https://www.flash.cn/flashplayer/3400323/install_flash_player_ppapi_cn.exe

**Comment by teknixstuff** [comment]
Okay, until FlashPatch is updated, I have made these hex replaces you can manually perform on `NPSWF64_34_0_0_323.dll` (64-bit NPAPI plugin)
E9 01 0F 84 98 00 00 00 83 E9 01 74 19 83 F9 02 0F 85 81 01 00 00 48 8B D6 48 8B CF E8 6A 63 00
E9 01 0F 84 98 00 00 00 83 E9 01 74 19 83 F9 02 E9 82 01 00 00 90 48 8B D6 48 8B CF E8 6A 63 00

40 48 8B 74 24 48 48 83 C4 20 5F 48 FF 60 18 CC 48 89 5C 24 10 48 89 6C 24 18 48 89 74 24 20 57
40 48 8B 74 24 48 48 83 C4 20 5F 48 FF 60 18 CC B8 01 00 00 00 C3 89 6C 24 18 48 89 74 24 20 57

B3 0D 04 00 48 8B 47 40 4C 89 7C 24 70 48 85 C0 74 28 80 B8 8F 03 00 00 00 75 1F 4C 8D BF E8 11
B3 0D 04 00 48 8B 47 40 4C 89 7C 24 70 48 85 C0 90 90 80 B8 8F 03 00 00 00 90 90 4C 8D BF E8 11

00 00 00 48 8B 5C 24 30 48 83 C4 20 5F C3 CC CC CC 48 89 5C 24 08 48 89 74 24 10 57 48 83 EC 20 48
00 00 00 48 8B 5C 24 30 48 83 C4 20 5F C3 CC CC CC B8 01 00 00 00 C3 89 74 24 10 57 48 83 EC 20 48

**Comment by wyf180** [comment]
Could every flash dll ocx use this patch? @teknixstuff

**Comment by wyf180** [comment]
I tried to replace all ,317 ,321 and _317 _321 in the source Patches.cs to  ,323 and _323,but it still can't check the 32bite ocx file after translation.

**Comment by teknixstuff** [comment]
> Could every flash dll ocx use this patch? @teknixstuff

No, this is specifically for the 64-bit NPAPI plugin. If you need a patch for another version, please tell me which one(s) you want and I'll try to make a patch for it.

**Comment by teknixstuff** [comment]
Here's the patches for the 32-bit NPAPI plugin (`NPSWF32_34_0_0_323.dll`)
BB EE FF 8B 06 8B CE FF 50 0C 5F 5E 8B E5 5D C3 55 8B EC 51 8B C1 53 56 57 8D B0 48 00 01 00 89
BB EE FF 8B 06 8B CE FF 50 0C 5F 5E 8B E5 5D C3 B8 01 00 00 00 C3 53 56 57 8D B0 48 00 01 00 89

38 02 00 00 57 E8 74 41 03 00 8B 47 20 53 85 C0 74 23 80 B8 37 02 00 00 00 75 1A 8D 9F 58 0B 00
38 02 00 00 57 E8 74 41 03 00 8B 47 20 53 85 C0 90 90 80 B8 37 02 00 00 00 90 90 8D 9F 58 0B 00

00 00 EB 06 C7 07 06 00 00 00 5F 5E 5D C2 0C 00 55 8B EC 53 56 8B F1 57 8B 7D 08 57 8D 4E 04 E8
00 00 EB 06 C7 07 06 00 00 00 5F 5E 5D C2 0C 00 8B 01 00 00 00 C3 F1 57 8B 7D 08 57 8D 4E 04 E8

**Comment by teknixstuff** [comment]
[CleanFlashPlayer_34.0.0.323.xpi.zip](https://github.com/user-attachments/files/18197718/CleanFlashPlayer_34.0.0.323.xpi.zip)
Also, for users of pale moon or old firefox versions, here's an XUL extension you can install that includes pre-patched versions of both 32-bit and 64-bit NPAPI flash player.

**Comment by wyf180** [comment]
I want to patch Flash32_34_0_0_323.ocx file.@teknixstuff

**Comment by wyf180** [comment]
https://www.mediafire.com/file/q053w6n6qv4s95p/Flash32_34_0_0_323.zip @teknixstuff

**Comment by teknixstuff** [comment]
> I want to patch Flash32_34_0_0_323.ocx file.@teknixstuff

Okay, will do. Although I suggest you try using pale moon with the NPAPI plugin, as it is secure and supports modern sites, unlike IE11, and can easily have flash player installed just by dropping the XPI file onto the app.

**Comment by teknixstuff** [comment]
[protectedmodehosts.zip](https://github.com/user-attachments/files/18217816/protectedmodehosts.zip)
[CleanFlashPlayer_34.0.0.323.xpi.zip](https://github.com/user-attachments/files/18217817/CleanFlashPlayer_34.0.0.323.xpi.zip)
[CleanFlash34.0.0.323_64.zip](https://github.com/user-attachments/files/18217818/CleanFlash34.0.0.323_64.zip)
[CleanFlash34.0.0.323_32.zip](https://github.com/user-attachments/files/18217819/CleanFlash34.0.0.323_32.zip)

Patched binaries for Flash Player 34.0.0.323
By Tech Stuff <me@teknixstuff.com>
Thanks to darktohka/FlashPatch for the original patches!

Note that generally the protected mode host files should only be needed for 32-bit NPAPI (and perhaps ActiveX).
64-bit variants do not appear to support protected mode, and PPAPI has it's own incompatible sandbox.
However, they are included anyway, in case anyone finds additional usages for them.
They have not been patched as they do not require it as far as I know.

Generally, you should prefer to use an updated browser that still supports NPAPI, such as Pale Moon or Basilisk.
Internet Explorer 11 is very outdated by now and should be avoided if possible.
Older versions of Firefox and Chrome are still fairly usable, however updated browsers should be preferred where possible.
I do not believe there is any updated browsers that support PPAPI or ActiveX, so those versions will likely not be needed,
unless you are trying to use an app that uses ActiveX, IE controls, Electron, or CEF, and requires Flash.

Typically these hex patches should be applicable to most future and past versions, however this is not guaranteed.
They should also work on the debug variants, however I have not found an installer for those and hence have been unable to test.

Additionally, if you have used certain installers for the unpatched version, you will find an adware Flash Helper Service has been bundled.
You can use the following commands in admin cmd to stop and remove it if present:

net stop "Flash Helper Service"
sc delete "Flash Helper Service"

You should also uninstall Flash Center if you previously used it to install Flash.

I plan on making a simplified installer to automatically download, unpack, patch,
and install any desired version of Flash Player, however I have not done that yet.

Files:
CleanFlashPlayer_34.0.0.323.xpi - 64-bit and 32-bit NPAPI plugin, packaged as an extension for Pale Moon, Basilisk, and older versions of Firefox.
^ This is generally the easiest and simplest method to use Flash.

NPSWF32_34_0_0_323.dll - 32-bit NPAPI plugin
FlashUtil32_34_0_0_323_Plugin.dll - 32-bit NPAPI protected mode helper
FlashUtil32_34_0_0_323_Plugin.exe - 32-bit NPAPI protected mode host

NPSWF64_34_0_0_323.dll - 64-bit NPAPI plugin
FlashUtil64_34_0_0_323_Plugin.dll - 64-bit NPAPI protected mode helper (in protectedmodehosts.zip)
FlashUtil64_34_0_0_323_Plugin.exe - 64-bit NPAPI protected mode host (in protectedmodehosts.zip)

pepflashplayer32_34_0_0_323.dll - 32-bit PPAPI plugin
FlashUtil32_34_0_0_323_pepper.dll - 32-bit PPAPI protected mode helper (in protectedmodehosts.zip)
FlashUtil32_34_0_0_323_pepper.exe - 32-bit PPAPI protected mode host (in protectedmodehosts.zip)

pepflashplayer64_34_0_0_323.dll - 64-bit PPAPI plugin
FlashUtil64_34_0_0_323_pepper.dll - 64-bit PPAPI protected mode helper (in protectedmodehosts.zip)
FlashUtil64_34_0_0_323_pepper.exe - 64-bit PPAPI protected mode host (in protectedmodehosts.zip)

Flash32_34_0_0_323.ocx - 32-bit ActiveX plugin
FlashUtil32_34_0_0_323_ActiveX.dll - 32-bit ActiveX protected mode helper
FlashUtil32_34_0_0_323_ActiveX.exe - 32-bit ActiveX protected mode host

Flash64_34_0_0_323.ocx - 64-bit ActiveX plugin
FlashUtil64_34_0_0_323_ActiveX.dll - 64-bit ActiveX protected mode helper (in protectedmodehosts.zip)
FlashUtil64_34_0_0_323_ActiveX.exe - 64-bit ActiveX protected mode host (in protectedmodehosts.zip)

Patches:
NPSWF64_34_0_0_323.dll
E9 01 0F 84 98 00 00 00 83 E9 01 74 19 83 F9 02 0F 85 81 01 00 00 48 8B D6 48 8B CF E8 6A 63 00
E9 01 0F 84 98 00 00 00 83 E9 01 74 19 83 F9 02 E9 82 01 00 00 90 48 8B D6 48 8B CF E8 6A 63 00

40 48 8B 74 24 48 48 83 C4 20 5F 48 FF 60 18 CC 48 89 5C 24 10 48 89 6C 24 18 48 89 74 24 20 57
40 48 8B 74 24 48 48 83 C4 20 5F 48 FF 60 18 CC B8 01 00 00 00 C3 89 6C 24 18 48 89 74 24 20 57

B3 0D 04 00 48 8B 47 40 4C 89 7C 24 70 48 85 C0 74 28 80 B8 8F 03 00 00 00 75 1F 4C 8D BF E8 11
B3 0D 04 00 48 8B 47 40 4C 89 7C 24 70 48 85 C0 90 90 80 B8 8F 03 00 00 00 90 90 4C 8D BF E8 11

00 00 00 48 8B 5C 24 30 48 83 C4 20 5F C3 CC CC CC 48 89 5C 24 08 48 89 74 24 10 57 48 83 EC 20 48
00 00 00 48 8B 5C 24 30 48 83 C4 20 5F C3 CC CC CC B8 01 00 00 00 C3 89 74 24 10 57 48 83 EC 20 48



NPSWF32_34_0_0_323.dll
BB EE FF 8B 06 8B CE FF 50 0C 5F 5E 8B E5 5D C3 55 8B EC 51 8B C1 53 56 57 8D B0 48 00 01 00 89
BB EE FF 8B 06 8B CE FF 50 0C 5F 5E 8B E5 5D C3 B8 01 00 00 00 C3 53 56 57 8D B0 48 00 01 00 89

38 02 00 00 57 E8 74 41 03 00 8B 47 20 53 85 C0 74 23 80 B8 37 02 00 00 00 75 1A 8D 9F 58 0B 00
38 02 00 00 57 E8 74 41 03 00 8B 47 20 53 85 C0 90 90 80 B8 37 02 00 00 00 90 90 8D 9F 58 0B 00

00 00 EB 06 C7 07 06 00 00 00 5F 5E 5D C2 0C 00 55 8B EC 53 56 8B F1 57 8B 7D 08 57 8D 4E 04 E8
00 00 EB 06 C7 07 06 00 00 00 5F 5E 5D C2 0C 00 8B 01 00 00 00 C3 F1 57 8B 7D 08 57 8D 4E 04 E8



pepflashplayer32_34_0_0_323.dll
18 02 00 00 53 E8 22 AA 11 00 8B 43 20 55 85 C0 74 23 80 B8 17 02 00 00 00 75 1A 8D AB D8 0A 00
18 02 00 00 53 E8 22 AA 11 00 8B 43 20 55 85 C0 90 90 80 B8 17 02 00 00 00 90 90 8D AB D8 0A 00

00 00 00 EB 06 C7 07 06 00 00 00 5F 5E C2 0C 00 53 56 8B F1 57 8B 7C 24 10 57 8D 4E 04 E8 02 01
00 00 00 EB 06 C7 07 06 00 00 00 5F 5E C2 0C 00 B8 01 00 00 00 C3 7C 24 10 57 8D 4E 04 E8 02 01

01 0F 84 82 00 00 00 83 E8 01 74 17 48 83 E8 01 0F 85 4B 01 00 00 53 8B CF E8 37 54 00 00 E9 3E
01 0F 84 82 00 00 00 83 E8 01 74 17 48 83 E8 01 E9 4C 01 00 00 90 53 8B CF E8 37 54 00 00 E9 3E

18 00 8D 4F 1C E8 07 DF D9 FF 5F 5E 8B E5 5D C3 55 8B E9 56 57 8D B5 48 00 01 00 8B CE E8 9F 90
18 00 8D 4F 1C E8 07 DF D9 FF 5F 5E 8B E5 5D C3 B8 01 00 00 00 C3 B5 48 00 01 00 8B CE E8 9F 90



pepflashplayer64_34_0_0_323.dll
93 32 20 00 49 8B 46 40 4C 89 7C 24 60 48 85 C0 74 28 80 B8 47 03 00 00 00 75 1F 4D 8D BE F0 10
93 32 20 00 49 8B 46 40 4C 89 7C 24 60 48 85 C0 90 90 80 B8 47 03 00 00 00 90 90 4D 8D BE F0 10

00 48 8B 5C 24 30 48 83 C4 20 5F C3 CC CC CC CC 48 89 5C 24 10 57 48 83 EC 20 48 8B FA 48 8B D9
00 48 8B 5C 24 30 48 83 C4 20 5F C3 CC CC CC CC B8 01 00 00 00 C3 48 83 EC 20 48 8B FA 48 8B D9

48 8D 4F 38 48 83 C4 38 5F 5B E9 D1 73 BD FF CC 40 55 53 57 41 55 48 8D 6C 24 C1 48 81 EC D8 00
48 8D 4F 38 48 83 C4 38 5F 5B E9 D1 73 BD FF CC B8 01 00 00 00 C3 48 8D 6C 24 C1 48 81 EC D8 00



Flash32_34_0_0_323.ocx
00 8B E5 5D C3 CC CC CC CC CC CC CC CC CC CC CC 55 8B EC 81 EC E0 00 00 00 A1 D0 DF A4 10 33 C5
00 8B E5 5D C3 CC CC CC CC CC CC CC CC CC CC CC B8 01 00 00 00 C3 00 00 00 A1 D0 DF A4 10 33 C5

AE 10 16 10 BA 10 16 10 C6 10 16 10 D2 10 16 10 55 8B EC 56 8B F1 8B 46 04 8D 4E 04 57 8B 7D 08
AE 10 16 10 BA 10 16 10 C6 10 16 10 D2 10 16 10 B8 01 00 00 00 C3 8B 46 04 8D 4E 04 57 8B 7D 08

B0 74 A2 00 00 53 E8 68 37 F2 FF 8B 43 24 85 C0 74 21 80 B8 73 A2 00 00 00 75 18 8D 8B 60 0B 00
B0 74 A2 00 00 53 E8 68 37 F2 FF 8B 43 24 85 C0 90 90 80 B8 73 A2 00 00 00 90 90 8D 8B 60 0B 00



Flash64_34_0_0_323.ocx
E9 01 0F 84 97 00 00 00 83 E9 01 74 19 83 F9 02 0F 85 9B 01 00 00 48 8B D6 48 8B CF E8 2B 67 00
E9 01 0F 84 97 00 00 00 83 E9 01 74 19 83 F9 02 E9 9C 01 00 00 90 48 8B D6 48 8B CF E8 2B 67 00

8B 74 24 40 48 83 C4 20 5F E9 2E 22 FA FF CC CC 4C 8B DC 49 89 5B 10 49 89 6B 18 49 89 73 20 57
8B 74 24 40 48 83 C4 20 5F E9 2E 22 FA FF CC CC B8 01 00 00 00 C3 10 49 89 6B 18 49 89 73 20 57

00 00 00 48 8B 5C 24 30 48 83 C4 20 5F C3 CC CC CC 48 89 5C 24 08 48 89 74 24 10 57 48 83 EC 20 48
00 00 00 48 8B 5C 24 30 48 83 C4 20 5F C3 CC CC CC B8 01 00 00 00 C3 89 74 24 10 57 48 83 EC 20 48

FF 48 8B 46 48 4C 89 A4 24 E8 00 00 00 48 85 C0 74 28 80 B8 D7 A3 00 00 00 75 1F 4C 8D A6 00 12
FF 48 8B 46 48 4C 89 A4 24 E8 00 00 00 48 85 C0 90 90 80 B8 D7 A3 00 00 00 90 90 4C 8D A6 00 12

**Comment by wyf180** [comment]
> [protectedmodehosts.zip](https://github.com/user-attachments/files/18217816/protectedmodehosts.zip) [CleanFlashPlayer_34.0.0.323.xpi.zip](https://github.com/user-attachments/files/18217817/CleanFlashPlayer_34.0.0.323.xpi.zip) [CleanFlash34.0.0.323_64.zip](https://github.com/user-attachments/files/18217818/CleanFlash34.0.0.323_64.zip) [CleanFlash34.0.0.323_32.zip](https://github.com/user-attachments/files/18217819/CleanFlash34.0.0.323_32.zip)
> 
> Info
> Files list
> Patches

Your flash ocx shared maybe for win8 and later,and can't work on my xp vm.

**Comment by darktohka** [comment]
FlashPatch has been updated to support version 34.0.0.323:
https://github.com/darktohka/FlashPatch/releases/tag/v1.28

Clean Flash Builds are available here:
https://github.com/darktohka/clean-flash-builds/releases/tag/v1.48 (Windows)
https://github.com/darktohka/clean-flash-builds/releases/tag/v1.47 (Mac)

Clean Flash Installer is available here:
https://gitlab.com/cleanflash/installer/-/releases/34.0.0.323

**Comment by teknixstuff** [comment]
> FlashPatch has been updated to support version 34.0.0.323: https://github.com/darktohka/FlashPatch/releases/tag/v1.28
> 
> Clean Flash Builds are available here: https://github.com/darktohka/clean-flash-builds/releases/tag/v1.48 (Windows) https://github.com/darktohka/clean-flash-builds/releases/tag/v1.47 (Mac)
> 
> Clean Flash Installer is available here: https://gitlab.com/cleanflash/installer/-/releases/34.0.0.323

Thanks!
