### ISSUE TITLE
doesn't work on Windows XP

### ISSUE THREAD

**Issue by Jantam11** [darktohka/FlashPatch#7]
i tried to use the tool but it doesn't work, so i tried use an program called alky to make it work and it does open the program but it gives me an error message when it tries to patch flash.
i know it probably won't work with xp, since it's such an obsolete OS but it's all this pc handles, so if you can't fix this, that's okay ill just keep using the projector to play the flash games i have, but i wont be able to the online flash games (the ones that require a login).

**Comment by darktohka** [comment]
If you want to use this tool on Windows XP, you're not going to have much success as this tool uses a recent version of the .NET Framework.

However, there's an alternative way to reap the benefits of this program on Windows XP.

Make your way to the following folder: `C:\Windows\System32\Macromed\Flash`, and decide which plugins you want to patch. Most likely, you'll have the opportunity to choose between the ActiveX OCX (for Internet Explorer), NPAPI DLL (for Mozilla Firefox), or PPAPI DLL (for Google Chrome)

Make note of these files, and copy them to a USB drive (if you're on a physical Windows XP machine) or copy them over to your guest OS (if you are emulating Windows XP).

Download FlashPatch on a recent Windows version (Windows 7 and above). Copy the DLLs/OCX you took from your Windows XP machine to a folder on your PC, and use the "Patch File..." button on FlashPatch. Choose all of the files you took from your Windows XP machine, and allow FlashPatch to patch them.

After FlashPatch's done with your files, simply copy paste the patched DLLs/OCX to your USB drive/copy them to your Windows XP machine, replacing the old binaries.

This way, you can patch Flash without ever having to install or run FlashPatch on your Windows XP machine.

**Comment by Jantam11** [comment]
i'll try that tonight, i'll have access to a win10 pc (not mine) so it should work, i'll give an answer if it has worked or not.

**Comment by Jantam11** [comment]
it worked like a charm! i don't know how i didn't remember to do this earlier! thx for the help!

**Comment by darktohka** [comment]
Glad to hear it's working! Enjoy using Flash!
